# Generated by Django 4.2.3 on 2023-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField(unique=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
